workflow:
  train: Yes
  test: Yes

directories:
  dataset_dir: ./genki4k
  model_dir: ./models
  output_dir: ./output

network:
  kernel_size: 5
  dilation: 1

training:
  batch_size: 32
  learning_rate: 1e-3
  epochs: 50
  test_split: 20
  validation_split: 10
  shuffle: Yes

  optimizer: adam
  loss: binary_crossentropy

  device: gpu
